:icons: font
:source-highlighter: rouge
:toc:
:toc-placement!:

= Annotations

With annotation it's possible in lapyst to annotate (or to add) metadata to key constructs of the lapyst language.

toc::[]

== Usage

Lets first look at how to write the annotation itself:

[source,lapyst]
----
@some_annotation <1>

@some_annotation(12) <2>

@some::namespaced::annotation <3>
----
<1> The annotation `some_annotation`, without parameters
<2> The annotation `some_annotation`, this time with a parameter.
<3> A annotation from some namespace

== Placement

Annotation itself can be placed at many places:

=== Above declarations

Annotations can places above everything that declares something:

[source,lapyst]
----
@namespace_annotation
namespace Test

    @shape_annotation
    shape MyTempl

        @field_annotation
        var int field;

        @method_annotation
        def method()
        end

    end

    @variable_annotation
    var int variable;

    @method_annotation
    def myFunction(
        @param_annotation int param1
    )
        # ...
    end

end

@function_annotation
def someFunction()

    @variable_annotation
    var int i;

end
----

=== Type annotation

Types also can be annotated with extra data:

[source,lapyst]
----
var Car car = new @type_annotation Car();

var @type_annotation int i;

var array[@type_annotation int] a;

shape MyContainer
    of [ @type_annotation T , @type_annotation int i, @type_annotation const j ]
    use [ @type_annotation Parent ]

    var @type_annotation int field;

    def (@type_annotation int, @type_annotation int) myFunction()
    end

end

// type annoation for typeless
var @type_annotation c;

c = new MyContainer[ @type_annotation int, 12, 1 ]();

f = cast d to @type_annotation F;
----

== Declaration

To create a custom annotation, you simply declare a shape that then is annotated with the meta-annotation `@Annotation`.

[source,lapyst]
----
@Annotation
shape MyAnnotation

    def MyAnnotation(int i)
        // ...
    end

end

@MyAnnotation(12)
shape MyShape
end
----

Since annotations are just shapes that are stored in the reflection system, you also can instantiate them just like a normal shape:

[source,lapyst]
----
new MyAnnotation(42);
----

To disable this behaviour, you can use multiple approaches:
- Annotate the custom annotation or the constructor with `@NotInstantiable`
- Enable the compiler option `annotation_not_instantiable` i.e. `{$enable annotation_not_instantiable}`

== Accessing

To access them, you need to use lapyst's reflaction framework.

// TODO: specify what this means / add some examples.