:icons: font
:source-highlighter: rouge
:toc:
:toclevels: 3
:toc-placement!:

= Syntax

This chapter covers the syntax of the lapyst language.

toc::[]

== Comments

In lapyst, line comments can begin either with `//` or `#` and run until the line ends (LN / `\n`). There are also mutline comments available which starts with `/&#42;` and ends with `&#42;/`:

[source,lapyst]
----
// this is a line not processed by the parser
# this line too

/*
 And here we have an whole region of the file
 that's not processed!
*/
----

I personaly believe the first thing one should learn in a new language is how to write comments. This can help newcomers to document what code is doing, outcomment code to test things and much much more.

Lapyst also supports doc-comments; a special form of comments where the standard toolset of lapyst searches for more information it then can use for documentational purposes. For more of that see Doc-Comments.

== The line terminator

This is an very-very special character: it tells lapyst that an portion of the code is complete and it can now "execute" it. This character is the semicolon `;`.

It's hard to explain this right at the start, you get it when we move further. The only thing to rember is that this character itself does not modify your data or anything. It's for lapyst to find yout when an portion of code ends and it can take it and do it's magic.

// Literals
ifdef::backend-pdf[]
include::literals.adoc[leveloffset=+1]
endif::[]
ifndef::backend-pdf[]
== Literals
See link:literals.adoc[here].
endif::[]

// Operators
ifdef::backend-pdf[]
include::operators.adoc[leveloffset=+1]
endif::[]
ifndef::backend-pdf[]
== Operators
See link:operators.adoc[here].
endif::[]

== Declaration of Variables

As we have written above: variables in lapyst need to be "declared", which means we must tell lapyst about there existence.

But for this we first need to learn about typed and non-typed variables:
- typed variables are typed (like their name implies) and can only hold data of their type For classes there is an extra case but we learn that in the chapter about classes.

- non-typed variables (sometimes also refered as type-less) are variables that don't care about what they are storing. You might heard this under the term "duck-typing".

We know now that there are two types, but what do they actually DO?
Well typed variables bring you the benefit that they also "check" the data you assign them to be of the correct type. This check is both done at compile time as well as runtime. The only "downside" of this is you cannot store arbitary data in them, but this is ok because typed variables gives us security that we indeed have data of an certain type stored.

If we do not want this, or need an looser "storage", one can use type-less variables. But be warned: they can (and will!) intruduce bugs to your code. Not without reason are languages that where initiali designed without types are begining now to intruduce an optional typed mode.

Now enough the words let the syntax speak:

[source,lapyst]
----
var int i;
----

This code above declares an variable named `i` of the type integer (`int`).
Remember `nil`: this variable is now in the "nothing" state!

[source,lapyst]
----
i == nil    // this would be `true`
----

Since we declared `i` now, we can "store" (assign) an integer to it:

[source,lapyst]
----
i = 12;
----

But we cannot store anything else in it:

[source,lapyst]
----
// all of the lines below will fail:
i = "hello";
i = true;
i = false;
i = 12.22;  // 12.22 is an float, so it dosnt fit here because we need an integer.
----

What we've used here as a type is an so calles native type. They are the most basic form of data and have all a literal to represent them:
- integer
- float
- string
- boolean
- regex

For more informations about all native types, their restrictions and more, see builtin types.

Here an full example:

[source,lapyst]
----
var int i;
i = 12;

// tipp: you also can merge the both lines together
var int j = 12;
----

[NOTE]
====
You might have noticed the simecolons in the examples.
Let us take a look at the first two lines of the full example:

[source,lapyst]
----
var int i;
i = 12;
----

The simecolon in the first line tells lapyst: 'Hey this statement is finished, you can process it now!' which in turn then has the result that the variable declaration gets effective.

The same as the second line: only this time its not an statement from the begin of the file, but rather since the last simecolon.
====

=== Constants

If Variables are one side of the medal, Constants are the other: both of them store data, but variables are variable, meaning we can change what we store in them. Constants on the other hand can only store one single thing, forever.

Because of this behaviour, constantants need an mandatory assignment in the declaration.

[source,lapyst]
----
const int a = 12;       // correct
const int b;            // incorrect, missing initializer
----

Another thing they that they distinguishes them from variables, is that they dont allow any form of assignment:

[source,lapyst]
----
const int a = 12;

a = 13;     // error
a += 2;     // also an error
----

=== Typeless

We now know how we declare typed variables and constants, but what about type-less?
Simple: just dont write the type!

[source,lapyst]
----
var a;
const b = 12;
----

This will create a type-less variable and/or constant.

[NOTE]
====
Type-less constants are possible but they have no benefit over typed constants, since we cannot store anything other than their initial value in them. This means type-less constants are more or less a shortcut for constants so we dosnt need to write the type out.
====

// Functions
ifdef::backend-pdf[]
include::functions.adoc[leveloffset=+1]
endif::[]
ifndef::backend-pdf[]
== Procedures/Functions
See link:functions.adoc[here].
endif::[]

// Branching
ifdef::backend-pdf[]
include::branching.adoc[leveloffset=+1]
endif::[]
ifndef::backend-pdf[]
== Branching
See link:branching.adoc[here].
endif::[]

// Loops
ifdef::backend-pdf[]
include::loops.adoc[leveloffset=+1]
endif::[]
ifndef::backend-pdf[]
== Loops
See link:loops.adoc[here].
endif::[]

// Error handling
ifdef::backend-pdf[]
include::error_handling.adoc[leveloffset=+1]
endif::[]
ifndef::backend-pdf[]
== Error Handling
See link:error_handling.adoc[here].
endif::[]

// Shapes
ifdef::backend-pdf[]
include::shapes.adoc[leveloffset=+1]
endif::[]
ifndef::backend-pdf[]
== Shapes
See link:shapes.adoc[here].
endif::[]

// Namespaces
ifdef::backend-pdf[]
include::namespaces.adoc[leveloffset=+1]
endif::[]
ifndef::backend-pdf[]
== Namespaces
See link:namespaces.adoc[here].
endif::[]

// Units
ifdef::backend-pdf[]
include::units.adoc[leveloffset=+1]
endif::[]
ifndef::backend-pdf[]
== Units
See link:units.adoc[here].
endif::[]

// Im/Exporting
ifdef::backend-pdf[]
include::im_export.adoc[leveloffset=+1]
endif::[]
ifndef::backend-pdf[]
== Im/Exporting
See link:im_export.adoc[here].
endif::[]

// Roles
ifdef::backend-pdf[]
include::roles.adoc[leveloffset=+1]
endif::[]
ifndef::backend-pdf[]
== Roles
See link:roles.adoc[here].
endif::[]

// Modules
ifdef::backend-pdf[]
include::modules.adoc[leveloffset=+1]
endif::[]
ifndef::backend-pdf[]
== Modules
See link:modules.adoc[here].
endif::[]

// Enums
ifdef::backend-pdf[]
include::enum.adoc[leveloffset=+1]
endif::[]
ifndef::backend-pdf[]
== Enum
See link:enum.adoc[here].
endif::[]

// Annotations
ifdef::backend-pdf[]
include::annotations.adoc[leveloffset=+1]
endif::[]
ifndef::backend-pdf[]
== Annotations
See link:annotations.adoc[here].
endif::[]

// Macros
ifdef::backend-pdf[]
include::macros.adoc[leveloffset=+1]
endif::[]
ifndef::backend-pdf[]
== Macros
See link:macros.adoc[here].
endif::[]

// References
ifdef::backend-pdf[]
include::references.adoc[leveloffset=+1]
endif::[]
ifndef::backend-pdf[]
== References
See link:references.adoc[here].
endif::[]