:icons: font
:source-highlighter: rouge
:toc:
:toclevels: 3
:toc-placement!:
:websiteflags: norun

= Syntax

This chapter covers the syntax of the lapyst language.

toc::[]

== Comments

In lapyst, line comments can begin either with `//` or `#` and run until the line ends (LN / `\n`). There are also mutline comments available which starts with `/&#42;` and ends with `&#42;/`:

[source,lapyst]
----
// this is a line not processed by the parser
# this line too

/*
 And here we have an whole region of the file
 that's not processed!
*/
----

I personaly believe the first thing one should learn in a new language is how to write comments. This can help newcomers to document what code is doing, outcomment code to test things and much much more.

Lapyst also supports doc-comments; a special form of comments where the standard toolset of lapyst searches for more information it then can use for documentational purposes. For more of that see Doc-Comments.

== The line terminator

This is an very-very special character: it tells lapyst that an portion of the code is complete and it can now "execute" it. This character is the semicolon `;`.

It's hard to explain this right at the start, you propably get it when we are further into the language. The only thing to rember is that this character itself does not modify your data or anything. It's for lapyst to find out when an portion of code ends and it can take it and do it's magic. :3

// Literals
ifdef::backend-pdf[]
include::literals.adoc[leveloffset=+1]
endif::[]
ifndef::backend-pdf[]
== Literals
See link:literals.adoc[here].
endif::[]

// Types
ifdef::backend-pdf[]
include::types.adoc[leveloffset=+1]
endif::[]
ifndef::backend-pdf[]
== Types
See link:types.adoc[here].
endif::[]

// Variables
ifdef::backend-pdf[]
include::variables.adoc[leveloffset=+1]
endif::[]
ifndef::backend-pdf[]
== Variables
See link:variables.adoc[here].
endif::[]

// Operators
ifdef::backend-pdf[]
include::operators.adoc[leveloffset=+1]
endif::[]
ifndef::backend-pdf[]
== Operators
See link:operators.adoc[here].
endif::[]

// Units
ifdef::backend-pdf[]
include::units.adoc[leveloffset=+1]
endif::[]
ifndef::backend-pdf[]
== Units
See link:units.adoc[here].
endif::[]

// Functions
ifdef::backend-pdf[]
include::functions.adoc[leveloffset=+1]
endif::[]
ifndef::backend-pdf[]
== Procedures/Functions
See link:functions.adoc[here].
endif::[]

// Branching
ifdef::backend-pdf[]
include::branching.adoc[leveloffset=+1]
endif::[]
ifndef::backend-pdf[]
== Branching
See link:branching.adoc[here].
endif::[]

// Loops
ifdef::backend-pdf[]
include::loops.adoc[leveloffset=+1]
endif::[]
ifndef::backend-pdf[]
== Loops
See link:loops.adoc[here].
endif::[]

// Error handling
ifdef::backend-pdf[]
include::error_handling.adoc[leveloffset=+1]
endif::[]
ifndef::backend-pdf[]
== Error Handling
See link:error_handling.adoc[here].
endif::[]

// Shapes
ifdef::backend-pdf[]
include::shapes.adoc[leveloffset=+1]
endif::[]
ifndef::backend-pdf[]
== Shapes
See link:shapes.adoc[here].
endif::[]

// Namespaces
ifdef::backend-pdf[]
include::namespaces.adoc[leveloffset=+1]
endif::[]
ifndef::backend-pdf[]
== Namespaces
See link:namespaces.adoc[here].
endif::[]

// Im/Exporting
ifdef::backend-pdf[]
include::im_export.adoc[leveloffset=+1]
endif::[]
ifndef::backend-pdf[]
== Im/Exporting
See link:im_export.adoc[here].
endif::[]

// Roles
ifdef::backend-pdf[]
include::roles.adoc[leveloffset=+1]
endif::[]
ifndef::backend-pdf[]
== Roles
See link:roles.adoc[here].
endif::[]

// Modules
ifdef::backend-pdf[]
include::modules.adoc[leveloffset=+1]
endif::[]
ifndef::backend-pdf[]
== Modules
See link:modules.adoc[here].
endif::[]

// Enums
ifdef::backend-pdf[]
include::enum.adoc[leveloffset=+1]
endif::[]
ifndef::backend-pdf[]
== Enum
See link:enum.adoc[here].
endif::[]

// Annotations
ifdef::backend-pdf[]
include::annotations.adoc[leveloffset=+1]
endif::[]
ifndef::backend-pdf[]
== Annotations
See link:annotations.adoc[here].
endif::[]

// Macros
ifdef::backend-pdf[]
include::macros.adoc[leveloffset=+1]
endif::[]
ifndef::backend-pdf[]
== Macros
See link:macros.adoc[here].
endif::[]

// References
ifdef::backend-pdf[]
include::references.adoc[leveloffset=+1]
endif::[]
ifndef::backend-pdf[]
== References
See link:references.adoc[here].
endif::[]