:icons: font
:source-highlighter: rouge
:toc:
:toc-placement!:
:websiteflags: norun

= Literals

The building blocks of every language, they express the most native data types of an language.

toc::[]

== Numbers

Numbers in lapyst are written like in pretty much every other language (this includes spoken ones such as english!):

[source,lapyst]
----
12 <1>
23.22 <2>
----
<1> Integer (non-fractional number)
<2> Floatingpoint number (number with a fractional part)

Floatingpoint numbers (or floats as we will call them from now on) are always Decimal based.

Integers on the other hand only defaults to the decimal representation. Lapyst include a bunch of others, each one distinguished from one another by it's prefix:

[source,lapyst]
----
1234567890 <1>
0x123456789ABCDEF0 <2>
0o12345670 <3>
0b10 <4>
----
<1> Decimal (10) based integer
<2> Hexa-decimal (16) based integer (prefix `0x`)
<3> Octal (8) based integer (prefix `0o`)
<4> Binary (2) based integer (prefix `0b`)

For readability lapyst also supports an `_` underscore between the letters of each number (but not in the prefix!):

[source,lapyst]
----
// this is valid
0b01000100_10000100

// this is not; underscore is inside prefix
0_b0100010010000100
----

Floats on the other hand can have optionally one of two suffixes:
[source,lapyst]
----
12.34F <1>
12.34f <1>

12.34D <2>
12.34d <2>
----
<1> Floatingpoint numbers, explicit default precision
<2> So called `doubles`: they have double the amount of space, so the have higher precision

Floatingpoint numbers that dosnt have a suffix are defaulting to `floats`, means lapyst works with them as if they had an `f` suffix.

== Booleans

Booleans are a simple datatype to express truthiness, this means they can either be `true` or `false`. These are by the way also the keywords in lapyst for the both only valid states of an boolean:

[source,lapyst]
----
true    // also known as 'yes' or '1'
false   // also known as 'no' or '0'
----

== Characters and Strings

A character represents a single letter or character of text and is encased in `'`,
while strings represent an full text / multiple characters in sequence, and are encased in `"`:

[source,lapyst]
----
'a'

"Hello, world!"

"Good morning, ${name}!" <1>
----
<1> This string uses interpolation, this means at the position of `${name}` the stringified value of the variable `name` is inserted.

Characters and strings also allow some special sequences of characters to better represent characters
that might not be easily typeable.

NOTE: the following examples use them inside a character, but they also can be used the same way in an string!

[source,lapyst]
----
'\n'    // line break

'\t'    // tabulator

'\r'    // cariage return

'\\'    // the character \ but since it's also used to denote escape
        // character we simply use them double to get the character itself.

'\v'    // vertical break

'\a'    // play a bell sound! (only in terminals, and only if they support it)

'\"'    // the character " but since it's also our delimiter for the string itself,
        // we prefix it with a \ to tell lapyst that we dont want the string to end here
----

=== ASCII values

Each character in a string is internally represented by a number. To now find out what this number means we have different "encodings", which are just big tables that say what number should be displayed as what character. One of such is ASCII.

To directly specify ASCII values (the numbers), you can use the escape sequence `\x`:

[source,lapyst]
----
'\x41' <1>
'\x20' <2>
----
<1> the letter `A` in ASCII
<2> an space in ASCII

To use it, you begin the sequence by writing `\x`, immediatly followed by two characters that together form a hexadecimal number. Therefore, the characters that are allowed are restricted to the range of `0` trough `9`, and `a` through `f` (case insensitive).

=== Unicode values

Another encoding is unicode (actually its UTF-8 or UTF-16 but lets keep it simple). Like with ASCII, you also can embedd these values directly into the string by using the `\u` escape sequence:

[source,lapyst]
----
'\u0041' <1>

'\u221E' <2>

'\u{1F9C0}' <3>
----
<1> ASCII `0x41` (the letter `A`) in unicode
<2> Mathematical symbol for infinity
<3> Emoji for a piece of cheese

There are two ways of writing the `\u` sequence:

- followed by 4 characters that together form a hexadecimal number.
- followed by a `{` which captures any character until the next `}` which together form a hexadecimal number.

Like `\x`, in both forms this means that the range of characters that should be interpret as a number is restricted to the range of `0` trough `9`, and `a` through `f` (case insensitive).

=== Escape sequences and interpolation

It is *not* allowed to construct escape sequences via interpolation, so this isnt working:

[source,lapyst]
----
"\u${0x221E}" <1>
----
<1> This will cause the compiler to raise an error

== Nil

Lapyst supports nullni-ness or rather nilni-ness, which means that variables can have a state of "nothing", where they hold... nothing. This is typically the case right after you decalred a variable but assignent nothing to it.

IMPORTANT: the behavior of `defaults to nil` is only true for some of lapyt's types. For example, neraly all basic types aren't by default nil but have their own default value. See link:./types.adoc#_basic_types[Basic types] for more information about this.

You can use the literal `nil` to check if a variable indeed holds nothing, or to reset an variable to this state of nothingness. This will also destroy objects an free them if neccessary.

[source,lapyst]
----
i === nil <1>
i = nil <2>
----
<1> checks if i has nothing in it. See Comparison operators on what `===` is.
<2> resets i to a state where it has nothing in it.

== Regex

Regexes (or regular expressions) are in lapyst first-class datatypes.
This means they have their own syntax too: they work a little like strings, but they dont support interpolation. They do howerver support to be multiline.

The various flags can only be expressed inside the regex itself.

[source,lapyst]
----
r"^hello"
r"(?i)abc"
----

For more information about regular expressions read the chapter about it here: Regular Expressions.

== Symbols

Symbols are like identifiers but unlike them, symbols are values, thus allowing us to use them just like numbers or strings!

[source,lapyst]
----
:hello_world
:"hello world"
----

As seen above, a symbol starts with an colon (`:`) and then continues until it hits the first whitespace or line terminator!
When you need spaces or a simecolon inside your symbols name, you can just quote the name. This works like the string: the symbol now continues until it hit's a second `"`.

NOTE: Symbols are a very powerfull value type because they are essentially named numbers.

== Arrays

An array in lapyst is simply an list of different values:

[source,lapyst]
----
[ 1, 2, 3, 4 ]
----

== Hashes

Hashes are an map-like structure meaning they store a value based on their key.

[source,lapyst]
----
{ "name": "John", key: 12 } <1>
----
<1> Note that keys can also be other variables!

== Identifiers

Sometimes we need to name things, to later refer to it by said name. These names are called "identifiers" (because the identify!).

There are a few rules for an identifier:

- the name cannot be a keyword (such as `true`, `false` or `end`)
- they need to only have alphanumerical characters in them (or underscores)
- they cannot have an whitespace or an linebreak in them
- they cannot start with an number

With that knowlage lets look at an quick example:
[source,lapyst]
----
myFancyVariableName

// these two dont work:
not-working

also not working
----
