:icons: font
:source-highlighter: rouge
:toc:
:toc-placement!:

= Roles

toc::[]

Roles are a lot like go-lang's interfaces. They are essentially "bags of methods".

What do we mean by this? Let's look at two example shapes:

[source,lapyst]
----
shape Car
    def drive(int meters)
        // ...
    end
end

shape Bike
    def drive(int meters)
        // ...
    end
end
----

As we see above, we have two shapes: `Car` and `Bike`, they both implement the method `drive`. Now we want to make a function that accepts both `Car` and `Bike` as an argument. There are a couple of approaches we could use here:

- overloading the new function, so one accepts `Car` and the other `Bike`
- changing both shapes to inherit from an single base shape

These two aproches seem relativly simple, but they have an major flaw: for example, wee need to have access to both shapes in order to refactor them to use one base shape. With overloading the problem is you then ONLY support `Car` and `Bike`, vor every other shape that also implements an `drive(int meters)` method, you'd have to write a new function.

But theres an solution to the problem: roles.

Roles are, like mentioned at the beginning, just bags of methods. They check if an incomming type has the right set of methods and if they do, the method can get called. For our example above this role would look like this:

[source,lapyst]
----
role Driveable
    dec drive(int meters); <1>
end
----
<1> We need to use `dec` here because we only declare a method and dont define it, since it has no body.

This new `Driveable` role matches any instance of shapes that have an `drive` method with the right set of parameters (and return types if declared).

So our new function could look like this:

[source,lapyst]
----
def move_to_town(Driveable d, Town t)
    d.drive(t.distance);
end
----

IMPORTANT: A role can also be empty, thus matching EVERY shape. The `any` type from the standard library is such an empty role.