:icons: font
:source-highlighter: rouge
:toc:
:toc-placement!:
:websiteflags: norun

= Types

In lapyst data can be strongly typed; which means you tell the compiler what type of data something should have and lapyst makes sure that only data that is compatible with that is used, and produces an error otherwise.

toc::[]

== Basic types

The most basic types lapyst has, are the ones xref:literals.adoc[Literals] themselfs have:

=== Integers

Integers like `123` or `0x2D4` use a range of types, which essentially group together two attributes: if they are signed and size.

The default value of all integers, signed and unsigned, is `0`.

|===
| type | alias | signed? | size | range

| `int8`  | `byte`  | signed   | 8 bit / 1 byte | -128 to 127
| `uint8` | `ubyte` | unsigned | 8 bit / 1 byte | 0 to 255

| `int16`  | `short`  | signed   | 16 bit / 2 bytes | -32,768 to 32,767
| `uint16` | `ushort` | unsigned | 16 bit / 2 bytes | 0 to 65,535

| `int32`  | `int`  | signed   | 32 bit / 4 bytes | -2,147,483,648 to 2,147,483,647
| `uint32` | `uint` | unsigned | 32 bit / 4 bytes | 0 to 4,294,967,295

| `int64`  | `long`  | signed   | 64 bit / 8 bytes | -9,223,372,036,854,775,808 to 9,223,372,036,854,775,807
| `uint64` | `ulong` | unsigned | 64 bit / 8 bytes | 0 to 18,446,744,073,709,551,615
|===

Literal integers are the type where they fit in best. Means a literal `12` will be `int8`! If you want that to be different, cast them to the desired type.

Casting integers can be risky; therefore lapyst only allows casts that widen the range of values; this means a `int8` can be casted to an `int16`, but not the otherway around. Casting signedness is always allowed (e.g. `int8` to `uint8` or in reverse).

An example:

[source,lapyst]
----
cast 12 to int16
----

=== Floats

Floatingpoint numbers (e.g. `12.34`), only have two types for them, and they correlate with their suffixes.

The default value of all floats is `0.0`.

|===
| type | alias | suffix | size | range | precision

| `f32` | `float` | `f` / `F` | 32 bit / 4 bytes | 1.2E-38 to 3.4E+38 | 6 decimal places
| `f64` | `double` | `d` / `D` | 64 bit / 8 bytes | 2.3E-308 to 1.7E+308 | 15 decimal places
|===

=== Booleans

Booleans (`true` / `false`) are of type `bool`, which in hardware is 1 bit wide.

The default value of all booleans is `false`.

Encoding:

- `true` becomes `1`
- `false` becomes `0`

=== Characters

Characters have a few storage classes:

|===
| type     | alias   | size

| `char8`  | `char`  | 8 bit / 1 byte
| `char16` | `wchar` | 16 bit / 2 bytes
| `char32` | `dchar` | 32 bit / 4 bytes
|===

You might ask: why the difference? Well because with unicode, one character is not equal to one byte anymore!

Characters can be converted back and forth between their integer counterparts. However this needs to always be explicitly done via casting:

[source,lapyst]
----
var int8 i = 'a'; // invalid, produces error

var int8 i = cast 'a' to int8; // correct way
----

Therefore, the default value of characters is always the numerical value `0`.

=== Strings

Lapyst supports two types of strings:

- `cstr`: this is a compatibility type and is equivalent to C's `char*`. Which means it's an c-style array of 8-bit values.

- `str`: the main string type of lapyst

Both variants support unicode characters. `ctsr` by deviding the character's data into chunks of 8-bit.

IMPORTANT: the character variant of `cstr` is `char8`, while `str` uses `char32`. This is imporant later if you want to retrieve single characters out of a string.

Default values for both are `nil`, which denotes the absence of a string.

=== Arrays

In lapyst there are like strings to variants of arrays:

`carray` is a compatibility type and is equivalent to C's array type. Accepts two generic parameters: `type` and an `size`. Because thy have an static size, they're somtimes also called "static arrays", which also means they cant be altered in their length once created:

[source,lapyst]
----
var carray[int, 3] = [ 1, 2, 3 ];
----

The other type are dynamic arrays, and these allow (like their name suggests), to be altered in their length:

[source,lapyst]
----
var array[int] = [ 1, 2, 3 ];
----

Both variants default to `nil`, which denotes the absence of any data.

=== Hashes / Maps

The type for maps is `map[K, V]`, where `K` stands for the type of the key, and `V` stands for the type of the value:

[source,lapyst]
----
var map[string, int] = { "a": 12, "b": 42 };
----

NOTE: Other languages may call them associative arrays.
