:icons: font
:source-highlighter: rouge
:toc:
:toc-placement!:

= Constructor

toc::[]

The constructor is an special method: it get's called when we instanciate a shape.

[source,lapyst]
----
shape Car
    var int kmh;

    def Car(int kmh) <1>
        self.kmh = kmh;
    end
end

var Car car1 = new Car(100); <2>
----
<1> This is an constructor, it's essentally a method thats named like the shape.
<2> We now need to supply arguments when we instanciate the shape.

NOTE: If you don't declare any explicit constructor, lapyst implicit declares an default constructor: it's the one we have called in previous examples. It takes no arguments and is essentially only there to setup some inner workings of the shape; but this is also done in all constructors defined by the programmer!

IMPORTANT: If you declare *ANY* constructor the default constructor is no longer created by lapyst, thus forcing you to either specify arguments when instanciating the shape or to define a custom constructor without parameters.

== Visibility

Constructors also have an visibility: this time it's not just bound to the shape but rather also the file or namespace the shape is declared in.

This means effectivly means:

- if an constructor is private, it can also be used in the file it's declared in, but only in the namespace it's declared in. But it can be not used outside the file even when in the same namespace. Only the shape itself can call this constructor then.

- if an constructor is protected the same as in private is possible but now its also possible for the same namespace but outside the file that declares the shape to use the constructor. The "level" here also refers to the level of namespace that can call the constructor.

- public is still what it is: public

To express the visibility, you simply use the same visibilty syntax as for methods.

== Inheritance

To call a parent's constructor, simply use `super()` inside the constructor. If not used, lapyst inserts it automatically to ensure proper initialization; it's inserted before your constructor so you have access to all initialized stuff from the parent(s).

== Named constructors

Lapyst allows for definition of named constructors:

[source,lapyst]
----
shape Car
    var int kmh;

    def Car(int kmh) <1>
        self.kmh = kmh;
    end

    def Car::from_miles(int mph) <2>
        # ...
    end
end

var Car car1 = new Car(100); <3>
var Car car2 = new Car::from_miles(100); <4>
----
<1> Normal constructor.
<2> Named constructor.
<3> Calls the normal constructor, can also be used in explicit form as `Car::Car`.
<4> Calls the named constructor `from_miles`

Apart from the additional name, named constructors behave excactly as the normal constructor, means that if you
have not calles `super()` in it, it's inserted automatically at the beginning.

NOTE: A named constructor DOES NOT automatically calls the normal constructor; it only calls the normal constructor of all supertypes.
